services:
  postgres:
    container_name: 'wessol-db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wessol_db'
      - 'POSTGRES_PASSWORD=QTJKLas4321'
      - 'POSTGRES_USER=postgres'
    volumes:
      - 'postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - 'spring-db'
networks:
  spring-db:
    driver: 'bridge'

volumes:
  postgres:
    driver: 'local'
