services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    depends_on:
      - postgres
    image: moataz2001/wessol-app-v4
    env_file: ./.env
    container_name: wessol_backend
    ports:
      - $PORT:$PORT
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: Moataz.noaman12@Gmail.com
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    ports:
      - "5050:80"
networks:
  spring-db:
    driver: 'bridge'

volumes:
  postgres:
    driver: 'local'
