services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    depends_on:
      - postgres
    image: moataz2001/wessol-app-v4
    env_file: ./.env
    container_name: wessol_backend
    ports:
      - $PORT:$PORT
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    environment:
      - DB_HOST=postgres
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
  wessol-site:
    container_name: wessol-site-app
    image: wessol-site
    restart: always
    ports:
      - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    environment:
      PGADMIN_DEFAULT_EMAIL: Moataz.noaman12@Gmail.com
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    ports:
      - "5050:80"
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
volumes:
  postgres:
    driver: 'local'
