spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: wessol_backend
  datasource:
    url: jdbc:postgresql://localhost:5432/wessol
    username: postgres
    password: QTJKLas4321
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json
server:
  port: 5487
#  servlet:
#    context-path: /api/v1/