spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: wessol_backend
  datasource:
    url: jdbc:postgresql://postgres:5432/wessol_db
    username: postgres
    password: QTJKLas4321
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://dpg-cpk7heect0pc73b3t460-a.oregon-postgres.render.com/wessol_database
#    username: moataz_noaman
#    password: Tk9sMkgjbF1l8jD8jU1EU4G0xmTEOZ3f
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

project:
  location: location/
base:
  url: "localhost:8080/"
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    api-docs:
      path: /api-docs
applications:
  security:
    secret-key: q1js4cSWr1cLqlbPS8mRR4v6xhs1ed4CiBHb71A87EO/zbI=
server:
  port: 3000
  servlet:
    context-path: /